$files = @(
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1003 (Div. 4)\A_Skibidus_and_Amog_u.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1003 (Div. 4)\B_Skibidus_and_Ohio.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1003 (Div. 4)\C_1_Skibidus_and_Fanum_Tax_easy_version.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1050 (Div. 4)\A_Sublime_Sequence.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1050 (Div. 4)\B_Lasers.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1050 (Div. 4)\C_Pacer.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1050 (Div. 4)\D_Destruction_of_the_Dandelion_Fields.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1050 (Div. 4)\E_Split.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1059 (Div. 3)\A_Beautiful_Average.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1059 (Div. 3)\B_Beautiful_String.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1059 (Div. 3)\C_Beautiful_XOR.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1062 (Div4)\A_Square.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1062 (Div4)\B_Your_Name.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1062 (Div4)\C_Isamatdin_and_His_Magic_Wand.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1062 (Div4)\D_Yet_Another_Array_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1062 (Div4)\E_khba_Loves_to_Sleep.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1065 (Div. 3)\A_Shizuku_Hoshikawa_and_Farm_Legs.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1065 (Div. 3)\B_Yuu_Koito_and_Minimum_Absolute_Sum.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1065 (Div. 3)\C_1_Renako_Amaori_and_XOR_Game_easy_version.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1071 (Div. 3)\A_Blackslex_and_Password.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1071 (Div. 3)\B_Blackslex_and_Showering.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1071 (Div. 3)\C_Blackslex_and_Number_Theory.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1072 (Div. 3)\A_Social_Experiment.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1072 (Div. 3)\B_Hourglass.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1072 (Div. 3)\C_Huge_Pile.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1073 (Div.2)\A_Array_Coloring.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1073 (Div.2)\B_MEX_Reordering.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1073 (Div.2)\C_Sorting_Game.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1073 (Div.2)\D_1_Sub_RBS_Easy_Version.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1074 (Div.4)\A_Perfect_Root.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1074 (Div.4)\B_Prefix_Max.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1074 (Div.4)\C_Shifted_MEX.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1074 (Div.4)\D_OutOfMemoryError.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1074 (Div.4)\E_The_Robotic_Rush.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1075 (Div. 2)\A_Table_with_Numbers.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1075 (Div. 2)\B_The_Curse_of_the_Frog.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1075 (Div. 2)\C_1_XOR_Convenience_Easy_Version.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1076 (Div. 3)\A. DBMB and the Array.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1076 (Div. 3)\B. Reverse a Permutation.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1076 (Div. 3)\C. Replace and Sum.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1076 (Div. 3)\D. Monster Game.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1077 (Div. 2)\A_Divisible_Permutation.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1077 (Div. 2)\B_Seats.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1078 (Div. 2)\A_Lawn_Mower.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1078 (Div. 2)\B_Offshores.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1078 (Div. 2)\C_Secret_message.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1080 (Div. 3)\A_Sieve_of_Erato_67_henes.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1080 (Div. 3)\B_Heapify_1.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1080 (Div. 3)\C_Dice_Roll_Sequence.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1084 (Div. 3)\A_Eating_Game.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1084 (Div. 3)\B_Deletion_Sort.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1084 (Div. 3)\C_Specialty_String.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1084 (Div. 3)\D_Portal.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1086 (Div. 2)\A_Bingo_Candies.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1086 (Div. 2)\B_Cyclists.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1086 (Div. 2)\C_Stamina_and_Tasks.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1087 (Div. 2)\A_Flip_Flops.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1087 (Div. 2)\B_Array.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1089 (Div. 2)\A_A_Simple_Sequence.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1089 (Div. 2)\B_Simply_Sitting_on_Chairs.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1089 (Div. 2)\C_1_A_Simple_GCD_Problem_Easy_Version.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1090 (Div. 4)\A_The_67_th_Integer_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1090 (Div. 4)\B_The_67_th_6_7_Integer_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1090 (Div. 4)\C_The_67_th_Permutation_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1090 (Div. 4)\D_The_67_th_OEIS_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Codeforces Round 1090 (Div. 4)\E_The_67_th_XOR_Problem.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Educational Codeforces Round 188 (Rated for Div. 2)\A_Passing_the_Ball.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Educational Codeforces Round 188 (Rated for Div. 2)\B_Right_Maximum.py'),
    (Get-Item 'C:\Users\LENOVO\Desktop\Transfer Folder\ACM\Codeforces Contests\Educational Codeforces Round 188 (Rated for Div. 2)\C_Spring.py'),
)
$groupedFiles = $files | Sort-Object @{Expression={Split-Path $_.Directory -Leaf}}, Name | Group-Object @{Expression={Split-Path $_.Directory -Leaf}}
